 language: java
 install: mvn surefire-report:report -DshowSuccess=true install
 sudo: required
 sudo: false
 
 deploy:
   edge: true
   provider: cloudfoundry
   username: sudarsan.x.james@verizon.com
   password: codered1
   api: https://api.run.pivotal.io
   organization: CodeRed
   space: development
